### ISSUE TITLE
Can't figure out how to run the tests

### ISSUE THREAD

**Issue by cnk** [johnpaulett/django-with-asserts#2]
I am trying to modify this project to take the parsed html rather than the entire response object (so I can do real unit tests rather than semi-integration tests). Before making changes, I want to run and then modify the tests. But I can't get the current test suite to run.

I have cloned the repository and created a virtual environment with lxml, cssselect, django, and the cloned repository (using  pip install -e ~/django-with-asserts). Then I tried to use the test.sh script to run the tests. From the top level directory, no tests get detected: 

```
(django-with-asserts) $ tests/test.sh
Creating test database for alias 'default'...
----------------------------------------------------------------------
Ran 0 tests in 0.000s
OK
Destroying test database for alias 'default'...
```

From within the tests directory, the tests are detected but can't import with_asserts.case. What am I missing / doing wrong here? 

```
(django-with-asserts/tests) $ ./test.sh 
./test.sh
Creating test database for alias 'default'...
E
======================================================================
ERROR: simple.tests.test_html (django.utils.unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: simple.tests.test_html
Traceback (most recent call last):
  File "/Users/cnk/virtualenvs/django-with-asserts/lib/python2.6/site-packages/django/utils/unittest/loader.py", line 260, in _find_tests
    module = self._get_module_from_name(name)
  File "/Users/cnk/virtualenvs/django-with-asserts/lib/python2.6/site-packages/django/utils/unittest/loader.py", line 238, in _get_module_from_name
    __import__(name)
  File "/Users/cnk/django-with-asserts/tests/simple/tests/__init__.py", line 1, in <module>
    from .test_html import *
  File "/Users/cnk/django-with-asserts/tests/simple/tests/test_html.py", line 2, in <module>
    from with_asserts.case import TestCase as HTMLTestCase
ImportError: No module named with_asserts.case

----------------------------------------------------------------------
Ran 1 test in 0.031s

FAILED (errors=1)
Destroying test database for alias 'default'...
```

**Comment by johnpaulett** [comment]
The [preferred method](https://django-with-asserts.readthedocs.org/en/latest/#contribute) for running the entire test suite is via tox, since it sets up the PYTHONPATH.

That said, I am able to run the suite from the root project.

```
(env)$ tests/test.sh
Creating test database for alias 'default'...
................
----------------------------------------------------------------------
Ran 16 tests in 0.086s
OK
Destroying test database for alias 'default'...
```

You may try to run `python setup.py develop` in the virtualenv, which will create a link in the virtualenv's site-packages.
